extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'airbnb-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'next/core-web-vitals'
  - 'prettier'
rules:
  # https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/402#issuecomment-368305051
  'jsx-a11y/anchor-is-valid':
    - error
    - components:
        - Link
      specialLink:
        - hrefLeft
        - hrefRight
      aspects:
        - invalidHref
        - preferButton
parserOptions:
  project: './tsconfig.json'
