extends:
  - 'plugin:tailwindcss/recommended'
  - 'airbnb'
  - 'airbnb/hooks'
  - 'airbnb-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'next/core-web-vitals'
  - 'prettier'
rules:
  # https://github.com/jsx-eslint/eslint-plugin-react/issues/2396
  # https://github.com/iamturns/eslint-config-airbnb-typescript/issues/203
  'react/require-default-props': off
  # To execute async process in onClick: https://github.com/typescript-eslint/typescript-eslint/pull/4623
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn:
        attributes: false
  # To execute async process in useEffect(): https://typescript-eslint.io/rules/no-floating-promises/#ignorevoid
  'no-void':
    - error
    - allowAsStatement: true
  # For Next.js: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/402#issuecomment-368305051
  'jsx-a11y/anchor-is-valid':
    - error
    - components:
        - Link
      specialLink:
        - hrefLeft
        - hrefRight
      aspects:
        - invalidHref
        - preferButton
  # For daisyUI
  'tailwindcss/no-custom-classname': off
  'tailwindcss/classnames-order':
    - error
    - prependCustom: true
  'jsx-a11y/label-has-associated-control': off
  # For versatileapi
  'no-underscore-dangle': off
parserOptions:
  project: './tsconfig.json'
